CREATE OR REPLACE TABLE
    "PROD_RAW_DB"."INKA"."MDE" (
        dateExtract TIMESTAMP_NTZ,
        primaryKey VARCHAR,
        productID VARCHAR,
        emailAddress VARCHAR,
        subscriptionId NUMBER (38, 0),
        OccupantID NUMBER (38, 0),
        subscriber NUMBER (38, 0),
        getspaper NUMBER (38, 0),
        rateCodeID VARCHAR,
        deliveryScheduleID VARCHAR,
        deliveryType VARCHAR,
        deliveryMethod VARCHAR,
        billingMethod VARCHAR,
        expirationDate TIMESTAMP_NTZ,
        endGraceDate TIMESTAMP_NTZ,
        startDate TIMESTAMP_NTZ,
        salesSource VARCHAR,
        salesSubSourceID VARCHAR,
        futureStopDate TIMESTAMP_NTZ,
        futureStopReason VARCHAR,
        stopDate TIMESTAMP_NTZ,
        stopReason VARCHAR,
        firstName VARCHAR,
        lastName VARCHAR,
        address VARCHAR,
        CityID VARCHAR,
        stateID VARCHAR,
        zipCode NUMBER (38, 0),
        zipExtension VARCHAR,
        county VARCHAR,
        phone VARCHAR,
        dateLastPayment TIMESTAMP_NTZ,
        datePaymentDecline TIMESTAMP_NTZ,
        cardExpireDate DATE,
        cardLast4 VARCHAR,
        weeklyRate NUMBER (38, 2),
        monthlyRate NUMBER (38, 2),
        routeID VARCHAR,
        autoRenewFlag BOOLEAN,
        dtiSolicitationCodes VARCHAR,
        isST BOOLEAN,
        isWP BOOLEAN,
        isDeliveryDay BOOLEAN,
        isDigitalOnly BOOLEAN,
        isDigitalRegistered BOOLEAN,
        dateRegistered TIMESTAMP_NTZ,
        isActivated BOOLEAN,
        isNewStart BOOLEAN,
        isVacRestart BOOLEAN,
        isEBill BOOLEAN,
        isWinback BOOLEAN,
        isGraceReminder BOOLEAN,
        isEZPay BOOLEAN,
        isCCdecline BOOLEAN,
        isMailSub BOOLEAN,
        isGraceAlert BOOLEAN,
        isCCExpire BOOLEAN,
        emailModifedDate TIMESTAMP_NTZ,
        emailSource VARCHAR,
        emailDomain VARCHAR,
        isValidDomain BOOLEAN,
        hygieneResult VARCHAR,
        isPrimary BOOLEAN,
        isShopBuyer BOOLEAN,
        marketArea VARCHAR,
        marketType VARCHAR,
        subscriptionStatus VARCHAR,
        salesCampaignCode VARCHAR,
        addrKey VARCHAR,
        autoRenewType VARCHAR,
        AddressID NUMBER (38, 0),
        SubBalance NUMBER (38, 2),
        SubBalance_Flag BOOLEAN,
        RateDescription VARCHAR,
        DeliveryScheduleDescription VARCHAR,
        eBillBeginDate DATE,
        pianoSubStatus VARCHAR,
        pianoTermName VARCHAR,
        pianoTermType VARCHAR,
        pianoStartDate TIMESTAMP_NTZ,
        pianoStopDate TIMESTAMP_NTZ,
        pianoExpirationDate TIMESTAMP_NTZ,
        pianoLastUpgradeDate TIMESTAMP_NTZ,
        pianoTermPeriod VARCHAR,
        pianoResourceID VARCHAR,
        autoRenewLength NUMBER (38, 0),
        autoRenewTerm VARCHAR,
        accountChangeFlag BOOLEAN,
        accountChangeTotalAmt VARCHAR,
        isPianoChurn120 BOOLEAN,
        isDigitalWinback BOOLEAN,
        pianoRegisteredTermID VARCHAR,
        pianoRegisteredTermName VARCHAR
    );

ALTER TABLE "PROD_RAW_DB"."INKA"."MDE" SET DATA_RETENTION_TIME_IN_DAYS = 7;