name: snowflake_user_provisioning
on:
  push:
    branches:
      - main
    paths:
      - 'users_roles.json'
jobs:
  version:
    name: "Sync users and roles"
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: startribune-prod
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: SECURITYADMIN
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: ADMIN
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: PROVISIONING_DB
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: USERS
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}


    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

        # Snowflake CLI installation
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "./config.toml"

      - name: Process user roles updates
        run: |
          snow stage copy --overwrite user_roles.json @test_stage
          snow sql -q "call BULK_INSERT_USER_ROLES_JSON('user_roles.json');"
          snow sql -q "call PROVISION_PENDING_ROLES();"
