name: snowflake_task_provisioning
on:
  push:
    branches:
      - main
    paths:
      - 'tasks/**'
jobs:
  version:
    name: "Sync tasks and procedures"
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: startribune-prod
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: FR_DEV_INGESTION
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: INGESTION_WH
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: DEV_RAW_DB
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: NAVIGA
      SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}


    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

        # Snowflake CLI installation
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "3.7.1"
          default-config-file-path: "./config.toml"

      - name: Process task changes
        run: |
          snow sql -f tasks/test.sql